openapi: 3.1.0
info:
  title: Dining API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
paths:
  /auth/signup:
    post:
      summary: User Registration/Create User
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userLogin'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createdUser'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
  /auth/login:
    post:
      summary: User Login
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userLogin'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/token'
        '400':
          description: NOT FOUND
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
  /locations:
    get:
      summary: Get all locations
      tags:
        - Dining Locations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/locationId'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
    post:
      summary: Create location
      tags:
        - Dining Locations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/location'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/locationId'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
  /locations/{id}:
    get:
      summary: Get Location by Id
      tags:
        - Dining Locations
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/locationId'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
    put:
      summary: Update Location by Id
      tags:
        - Dining Locations
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/location'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/locationId'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
    delete:
      summary: Delete location by Id
      tags:
        - Dining Locations
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        '204':
          description: No content
          content:
            application/json:
              schema: null
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
  /menus:
    get:
      summary: Get all menus
      tags:
        - Menus
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/menusId'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
    post:
      summary: Create menu
      tags:
        - Menus
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/menus'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/menusId'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
  /menus/{id}:
    get:
      summary: Get Menu by Id
      tags:
        - Menus
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/menusId'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
    put:
      summary: Update Menu by Id
      tags:
        - Menus
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/menus'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/menusId'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
    delete:
      summary: Delete Menu by Id
      tags:
        - Menus
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        '204':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
  /users:
    get:
      summary: List all users (admin-only)
      tags:
        - Users
      security:
        - BearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/userId'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
  /users/me:
    get:
      summary: Get current user
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/userId'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
    put:
      summary: Update current user's information
      tags:
        - Users
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateUser'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/userId'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
    delete:
      summary: Delete current user
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        '204':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
  /users/me/favorites:
    get:
      summary: Get current user's favorites
      tags:
        - User Favorites
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/favorites'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
  /users/me/favorites/{id}:
    put:
      summary: Add FoodItem to Favorites by foodId
      tags:
        - User Favorites
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/favorites'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
    delete:
      summary: Delete FoodItem from Favorites by foodId
      tags:
        - User Favorites
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/favorites'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    userLogin:
      type: object
      properties:
        email:
          type: string
          example: test@uncc.edu
        password:
          type: string
          example: test1234
    createdUser:
      type: string
      example: New user created with an id of 2
    BadRequest:
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: ../schemas/ValidationError.yaml
    token:
      type: string
      example: sample token
    locationId:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Example
        description:
          type: string
          example: This is an example location.
    location:
      type: object
      properties:
        name:
          type: string
          example: Example
        description:
          type: string
          example: This is an example location.
    menusId:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Example Menu
        mealType:
          type: string
          example: Breakfast
        date:
          type: string
          example: placeholder string
        diningLocationId:
          type: integer
          example: 1
    menus:
      type: object
      properties:
        name:
          type: string
          example: Example Menu
        mealType:
          type: string
          example: Breakfast
        diningLocationId:
          type: integer
          example: 1
    userId:
      type: object
      properties:
        id:
          type: integer
          example: 1
        email:
          type: string
          example: test@gmail.com
        role:
          type: string
          enum:
            - USER
            - ADMIN
          example: USER
        preferences:
          type: string
          example: placeholder
        notificationEnabled:
          type: boolean
          example: false
        favoriteFoods:
          type: string
          example: placeholder
    updateUser:
      type: object
      properties:
        email:
          type: string
          example: test@gmail.com
        password:
          type: string
          example: test1234
        notificationEnabled:
          type: boolean
          example: false
    favorites:
      type: object
      properties:
        test:
          type: string
          example: Placeholder for food refactor
